return {
  -- 'sindrets/diffview.nvim',
  -- 'kosayoda/nvim-lightbulb',
  -- 'jubnzv/virtual-types.nvim',
  -- 'ap/vim-css-color',
  -- 'wfxr/minimap.vim',
  -- 'pechorin/any-jump.nvim',
  -- 'dylanaraps/wal.vim',
  -- 'lvimuser/lsp-inlayhints.nvim',
  -- 'f-person/git-blame.nvim',
  -- 'ggandor/lightspeed.nvim',
  -- 'hrsh7th/cmp-nvim-lsp',
  -- 'hrsh7th/cmp-nvim-lua',
  -- 'hrsh7th/cmp-buffer',
  -- 'hrsh7th/cmp-path',
  -- 'hrsh7th/cmp-cmdline',
  -- 'junegunn/fzf',
  -- 'junegunn/fzf.vim',
  -- 'L3MON4D3/LuaSnip',
  -- 'jpalardy/vim-slime',
  'mfussenegger/nvim-jdtls',
  'kana/vim-textobj-user',
  { 'kana/vim-textobj-fold', dependencies = 'kana/vim-textobj-user' },
  { 'kana/vim-textobj-indent', dependencies = 'kana/vim-textobj-user' },
  { 'kana/vim-textobj-line', dependencies = 'kana/vim-textobj-user' },
  { 'sgur/vim-textobj-parameter', dependencies = 'kana/vim-textobj-user' },
  'tpope/vim-repeat',
  {
    'tpope/vim-surround',
    config = function()
      vim.g.surround_no_insert_mappings = true
    end,
  },
  { 'kevinhwang91/nvim-bqf', ft = 'qf' },
  {
    'junegunn/fzf',
    -- run = function()
    --   vim.fn['fzf#install']()
    -- end,
  },

  {
    'nvim-neotest/neotest',
    conf = 'neotest',
    cmd = { 'Neotest' },
    dependencies = {
      'marilari88/neotest-vitest',
    },
  },

  -- 'mfussenegger/nvim-dap',
  -- -- 'mtikekar/nvim-send-to-term',
  -- 'nvim-lua/plenary.nvim',
  -- 'nvim-neotest/neotest-python',
  -- 'nvim-neotest/neotest-plenary',
  -- 'nvim-treesitter/nvim-treesitter-textobjects',
  -- 'onsails/diaglist.nvim',
  -- 'onsails/lspkind-nvim',
  -- 'p00f/clangd_extensions.nvim',
  -- 'rouge8/neotest-rust',
  -- 'shunsambongi/neotest-testthat',
  -- 'ray-x/cmp-treesitter',
  -- 'RRethy/nvim-treesitter-textsubjects',
  -- 'RRethy/nvim-base16',
  -- 'saadparwaiz1/cmp_luasnip',
  -- 'SirVer/ultisnips',
  -- 'stevearc/dressing.nvim',
  -- 'chrisbra/Colorizer',
}
